#!python

import os
from pathlib import Path
from argparse import ArgumentParser

parser = ArgumentParser(prog="brun", description="C++ build and run script")

parser.add_argument("file", help="C++ file name")
parser.add_argument("-i", "--input", help="Input file name")
parser.add_argument("-o", "--output", help="Output file name")

args = parser.parse_args()

path = Path(args.file)
path = path.parent / path.stem

command = f"build {path} && ulimit -s 262144 && ulimit -v 1048576 && ./{path}"

if args.input:
    command += f" < {args.input}"

if args.output:
    command += f" > {args.output}"

os.system(command)
