#!/usr/bin/env python3

import os
from pathlib import Path
from argparse import ArgumentParser

parser = ArgumentParser(prog="build", description="C++ build script")

parser.add_argument("file", help="C++ file name")

args = parser.parse_args()

path = Path(args.file)
path = path.parent / path.stem

os.system(f"g++ -std=c++17 -Wall -O2 -o {path} {path}.cpp")
